name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba
    - name: Install dependencies
      run: |
        mamba env update --file environment-test.yml --name base
    - name: Install current project in dev mode
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        mamba install -c conda-forge pytest
    - name: Test with pytest
      run: |
        pytest -p no:faulthandler

